owner: n3oltd
repo: status

sites:
  - name: Engage
    url: https://n3o.cloud/eu1/enage

status-website:
  cname: status.n3o.ltd
  logoUrl: https://raw.githubusercontent.com/n3oltd/status/master/static/n3o-logo.svg
  name: N3O Status
  theme: light
  css: "body { margin-top: 2rem; } nav { display: none; }"
      
i18n:
  footer: All times are in UTC

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
